# Generated by Django 5.0.2 on 2024-06-14 17:49

import datetime
import reservation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker_data', models.CharField(help_text='Name and Surname', max_length=200)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, help_text='Starting time')),
                ('duration', models.PositiveSmallIntegerField(choices=[(30, '30 minutes'), (60, '1 hour'), (90, '1.5 hours'), (120, '2 hours')], default=60)),
                ('end_time', reservation.models.CustomDateTimeField(default=datetime.datetime.now, help_text='Final time')),
                ('notes', models.TextField(blank=True, help_text='Add description', null=True)),
                ('cancel_event', models.BooleanField(default=False, help_text='Cancel this event')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, help_text='Add description', null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Scheduling',
                'ordering': ('-day', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ('start',),
            },
        ),
    ]
